version: '3'

services:
  website-service:
    build: ./website
    volumes:
      - ./website:/usr/src/app/website
    ports:
      - 80:80
  database-service:
    build: ./database
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
